# Generated by Django 4.2.4 on 2023-08-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footballer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'footballer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('minute', models.BigIntegerField()),
            ],
            options={
                'db_table': 'goal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('is_over', models.BooleanField()),
            ],
            options={
                'db_table': 'match',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('city', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'referee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('max_people', models.BigIntegerField()),
            ],
            options={
                'db_table': 'stadium',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('emblem_path', models.TextField()),
            ],
            options={
                'db_table': 'team',
                'managed': False,
            },
        ),
    ]
