# Generated by Django 4.2.4 on 2023-09-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('password', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sector', models.BigIntegerField()),
                ('row', models.BigIntegerField()),
                ('place', models.BigIntegerField()),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketSales',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ticket_sales',
                'managed': False,
            },
        ),
    ]
